@extends('layouts.site')

@section('title', $project->title.' — '.$settings->name)
@section('description', $project->summary)

@section('content')
<article>
    <header class="site-container py-16 sm:py-24"><a href="{{ route('work') }}" class="text-sm font-semibold text-blue-600 dark:text-blue-400">← All work</a><div class="mt-8 max-w-4xl"><p class="section-kicker">{{ $project->category }}</p><h1 class="mt-4 text-5xl font-black tracking-[-.05em] sm:text-7xl">{{ $project->title }}</h1><p class="mt-7 max-w-3xl text-xl leading-9 text-slate-600 dark:text-slate-300">{{ $project->summary }}</p><div class="mt-7 flex flex-wrap items-center gap-3 text-sm"><span class="rounded-full bg-blue-50 px-4 py-2 font-semibold text-blue-700 dark:bg-blue-500/10 dark:text-blue-300">{{ $project->status ?: 'Project' }}</span>@if($project->client)<span class="text-slate-500">Built for {{ $project->client }}</span>@endif</div></div></header>
    @if ($project->image_path)<div class="site-container pb-16"><div class="overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-100 shadow-2xl shadow-blue-950/10 dark:border-white/10 dark:bg-slate-900"><img src="{{ str_starts_with($project->image_path, '/') || str_starts_with($project->image_path, 'http') ? $project->image_path : asset('storage/'.$project->image_path) }}" alt="{{ $project->title }} interface" class="w-full object-cover object-top"></div></div>@endif
    <section class="border-y border-slate-200/80 bg-slate-50/70 py-20 dark:border-white/10 dark:bg-white/[.025]"><div class="site-container grid gap-12 lg:grid-cols-3">
        @if($project->challenge)<div><p class="section-kicker">The challenge</p><p class="mt-4 text-lg leading-8 text-slate-600 dark:text-slate-300">{{ $project->challenge }}</p></div>@endif
        @if($project->solution)<div><p class="section-kicker">The solution</p><p class="mt-4 text-lg leading-8 text-slate-600 dark:text-slate-300">{{ $project->solution }}</p></div>@endif
        @if($project->responsibilities)<div><p class="section-kicker">My role</p><p class="mt-4 text-lg leading-8 text-slate-600 dark:text-slate-300">{{ $project->responsibilities }}</p></div>@endif
    </div></section>
    @if($project->technologies)<section class="site-container py-16"><p class="section-kicker">Built with</p><div class="mt-5 flex flex-wrap gap-2">@foreach($project->technologies as $technology)<span class="rounded-full border border-slate-200 bg-white px-4 py-2 font-mono text-sm text-slate-600 dark:border-white/10 dark:bg-white/5 dark:text-slate-300">{{ $technology }}</span>@endforeach</div></section>@endif
    @php($gallery = collect($project->gallery ?? [])->unique()->reject(fn ($image) => $image === $project->image_path))
    @if($gallery->isNotEmpty())<section class="site-container pb-20"><div class="grid gap-6 md:grid-cols-2">@foreach($gallery as $image)<div class="overflow-hidden rounded-2xl border border-slate-200 bg-slate-100 dark:border-white/10 dark:bg-slate-900"><img src="{{ str_starts_with($image, '/') || str_starts_with($image, 'http') ? $image : asset('storage/'.$image) }}" alt="{{ $project->title }} screen {{ $loop->iteration }}" class="w-full object-cover object-top" loading="lazy"></div>@endforeach</div></section>@endif
    <section class="site-container pb-20 sm:pb-28"><div class="rounded-[2rem] bg-blue-600 px-7 py-12 text-white sm:px-12 sm:py-14"><div class="flex flex-col justify-between gap-8 md:flex-row md:items-center"><div><h2 class="text-3xl font-black tracking-tight">Interested in something like this?</h2><p class="mt-3 text-blue-100">Let’s talk about the result you need, without the technical overwhelm.</p></div><div class="flex flex-wrap gap-3">@if($project->url)<a href="{{ $project->url }}" target="_blank" rel="noreferrer" class="button-secondary border-white/30 bg-white text-slate-950">Visit project ↗</a>@endif<a href="{{ route('contact') }}" class="inline-flex min-h-12 items-center justify-center rounded-xl bg-slate-950 px-6 font-bold text-white">Start a project</a></div></div></div>
        @if($previous || $next)<nav class="mt-10 grid gap-4 sm:grid-cols-2" aria-label="More projects">@if($previous)<a href="{{ route('work.show', $previous) }}" class="rounded-2xl border border-slate-200 p-5 transition hover:border-blue-500 dark:border-white/10"><span class="text-xs uppercase tracking-wider text-slate-500">Previous project</span><strong class="mt-1 block">← {{ $previous->title }}</strong></a>@else<div></div>@endif @if($next)<a href="{{ route('work.show', $next) }}" class="rounded-2xl border border-slate-200 p-5 text-right transition hover:border-blue-500 dark:border-white/10"><span class="text-xs uppercase tracking-wider text-slate-500">Next project</span><strong class="mt-1 block">{{ $next->title }} →</strong></a>@endif</nav>@endif
    </section>
</article>
@endsection
